.PHONY: android ios
filename=ui
android:
	mkdir -p "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/unpack"
	cp ../../tmp/res_android/unpack/*.png "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/unpack"
	cp ../../tmp/res_android/unpack/*.jpg "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/unpack"

ios:
	mkdir -p "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/unpack"
	cp ../../tmp/res_ios/unpack/*.png "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/unpack"
	cp ../../tmp/res_android/unpack/*.jpg "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/unpack"
