.PHONY: android ios
filename=fonts
android:
	cp ../../tmp/res_android/fonts/*.png "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/"
	cp ../../tmp/res_android/fonts/*.fnt "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/"

ios:
	cp ../../tmp/res_android/fonts/*.png "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/"
	cp ../../tmp/res_android/fonts/*.fnt "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/"
