.PHONY: android ios
filename=fonts
android:
	mkdir -p "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/fonts"
	cp ../../tmp/res_android/fonts/*.png "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/fonts"
	cp ../../tmp/res_android/fonts/*.fnt "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/fonts"

ios:
	mkdir -p "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/fonts"
	cp ../../tmp/res_android/fonts/*.png "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/fonts"
	cp ../../tmp/res_android/fonts/*.fnt "../../raw/spritebuilder_zombie-zoo.spritebuilder/Packages/SpriteBuilder Resources.sbpack/fonts"
